### ISSUE TITLE
Release #114 for Local development

### ISSUE THREAD

**Issue by babaMar** [kislyuk/watchtower#118]
I see in https://github.com/kislyuk/watchtower/pull/114 a patch for local development has been implemented, any idea why it hasn't been released?

**Comment by kislyuk** [comment]
Hello, thank you for your interest. A release has not yet been made for this PR because as the maintainer of this library, I have a number of other responsibilities which have recently kept me occupied. I will make a release as soon as I can, in the meantime you can always install the package from the git repository. If you wish to help, you can sponsor the project using the "Sponsor" button at the top of the page, or contribute a mock testing environment that might obviate the need for manual testing with live AWS credentials.

**Comment by kislyuk** [comment]
Released in v1.0.0
