### ISSUE TITLE
[bug] create_log_group option is not really idempotent

### ISSUE THREAD

**Issue by tinproject** [kislyuk/watchtower#146]
According to code:
> :param create_log_group:
        Create CloudWatch Logs log group if it does not exist.  **True** by default.
    :type create_log_group: Boolean

create_log_group will create the Cloudwatch Log Group if it not exists.

In the case that the log-group already exists, but the IAM policy assigned does not provides permission to create the log-group, watchtower will fail with an `botocore.exceptions.ClientError: An error occurred (AccessDeniedException) when calling the CreateLogGroup operation: ...` exception.

The expected behavior is to just work properly, as the log-group already exists (and it's accessible on my case).

**Comment by kislyuk** [comment]
Sorry, I don't think there is a good way to fix this. Ignoring the error and failing later is just as bad. If you don't want to create the log group, then pass create_log_group=False. Your impression is also incorrect; create_log_group is idempotent in the use case described, since in your situation calling it multiple times yields the same effect.
