### ISSUE TITLE
Integrating With Systemd

### ISSUE THREAD

**Issue by redixhumayun** [kislyuk/watchtower#169]
I'm using this library for logging in a Python3 multi-processing project. I have used `systemd` to daemonize the service and start-up automatically on boot and on quitting the program.

Now, my issue is that the library works beautifully when I run the program directly from the command line. However, when I run the program through `systemd`, for some reason my logs get swallowed and don't show up on AWS.

I have confirmed that my logs are correctly showing up in `journald` but for some reason they don't get recorded in AWS.

Is there a specific way to handle logging when running with `systemd`?

**Comment by kislyuk** [comment]
Thanks for your interest in Watchtower. This library is completely agnostic with respect to systemd. The problem you are facing most likely has to do with a misconfigured environment, for example a lack of AWS credentials in the process environment. To begin diagnosing the problem, you need to get the full stderr stream from your process and see the errors emitted there.

I'm going to close this issue for now since it doesn't appear to be a bug in Watchtower. If you see something specific that you think should be improved, please feel free to comment or file another issue.

**Comment by redixhumayun** [comment]
@kislyuk This is exactly right. I came back here to comment saying that it was an AWS region issue.

For any one facing this issue, running `aws configure` and `sudo aws configure` allow you to configure two different sets of credentials. When running a `systemd` unit file, it's run as root. So, you need to configure the aws region by running `sudo aws configure`
