### ISSUE TITLE
json formatter

### ISSUE THREAD

**Issue by baddoxx** [kislyuk/watchtower#176]
Hi - firstly thanks for creating this log handler, it's simplified things for me greatly.

however I'm unable to get things to work as described in the doco.; the [example json formatter](https://kislyuk.github.io/watchtower/#examples-python-logging-config) just won't work, and cannot produce the results described in the documentation.  I've tried to modify it myself but I cannot find a way to make the log formatter correctly handle dictionaries passed to it, and the resulting message sent to CW is not valid json (contains ' instead of ") and is parsed as a string only.

e.g. my formatter attempt
`format: '{ "timestamp" : "%(asctime)s", "process" : "%(process)d", "levelname" : "%(levelname)s", "name" : "%(name)s", "function" : "%(funcName)s", "line" : "%(lineno)s", "message" : "%(message)s" }'`

and the resulting message sent to CW

```
{
    "timestamp": "2022-07-27 06:01:20,679",
    "process": "18421",
    "levelname": "CRITICAL",
    "name": "__main__",
    "function": "main",
    "line": "9",
    "message": "{'request': 'hello', 'metadata': {'size': 666}}"
}
```

can you please advise what the json formatter should be in the logging config? 

best
Richard
[cwtest.py.txt](https://github.com/kislyuk/watchtower/files/9195537/cwtest.py.txt)

**Comment by kislyuk** [comment]
Thank you for your interest in Watchtower. If you want to log JSON, do not use a formatter that formats your message as a non-JSON string.

I agree the documentation of the logging system YAML config was misleading. It was originally contributed by a third party and I failed to thoroughly vet it. I deleted all mention of formatters from that part of the documentation.

To be clear, JSON and nested JSON objects are supported and have been supported by Watchtower since day one, as illustrated in line 6 of the first code block in the readme.
