### ISSUE TITLE
Help: How to skip pushing logs from certain global logger

### ISSUE THREAD

**Issue by overide** [kislyuk/watchtower#191]
I've made changes in my `celery` app config to push celery logs on the cloudwatch but I'm interested in only task related logs and nothing else.  But what i can see on the cloud watch, it pushed logs from all celery related logs - 

![image](https://github.com/kislyuk/watchtower/assets/19911594/4bd8b214-22ed-4f1b-857a-af3005c38e42)

I'm only interested in the `celery.app.trace-23-10-10` log or better if i can merge all celery related logs into one.

How can I do that?

Thank you!

**Comment by overide** [comment]
I think adding a filter on the watchtower handler which filters out the undesirable log will be a solution.

 But I still don't know how to sens all celery-related logs to a single stream.

**Comment by kislyuk** [comment]
Hello, thank you for your interest in watchtower.

This library is a log handler and does not filter any logs except those related to its own operation. To merge logs into one log group, you can specify the log group name instead of using the default log group name that corresponds to the logger name. The Python logging library natively supports filtering logs using a variety of techniques, including filters (https://docs.python.org/3/library/logging.html#logging.Logger.addFilter), to accomplish what you describe.

**Comment by kislyuk** [comment]
Since this issue is not describing a bug in watchtower, I'm going to close it for now.
