### ISSUE TITLE
Ignore 0-length messages

### ISSUE THREAD

**Issue by knovak** [kislyuk/watchtower#43]
Currently watchtower fails when the length of the logged message is zero (see below).  No subsequent log entries are made to cloudwatch.  Other log handlers (to files or streams) do not fail.  If cloudwatch demands a 1-character length minimum, then send a space.

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 764, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/site-packages/watchtower/__init__.py", line 184, in batch_sender
    self._submit_batch(cur_batch, stream_name)
  File "/usr/lib/python2.7/site-packages/watchtower/__init__.py", line 109, in _submit_batch
    response = self.cwl_client.put_log_events(**kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 159, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 470, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 523, in _convert_to_request_dict
    api_params, operation_model)
  File "/usr/lib/python2.7/site-packages/botocore/validate.py", line 270, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
ParamValidationError: Parameter validation failed:
Invalid length for parameter logEvents[58].message, value: 0, valid range: 1-inf
Invalid length for parameter logEvents[96].message, value: 0, valid range: 1-inf

 (Watchtower actually hangs and cannot be interrupted after this error. )

**Comment by dvukolov** [comment]
Replacing zero-length messages with spaces seems to be the proper way, since message length validation happens at the botocore level. As an example I'm logging output from a test docker container:
```
$ docker run hello-world
Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
[redacted]
```
An empty row resulting from a logging.info("") call will display correctly both in the console and in CloudWatch Logs if one substitutes that empty message with a space. The fix is trivial, I can make a PR if you agree with the approach.

**Comment by kislyuk** [comment]
Sounds good, although if we can get away with replacing it with a newline character, that would be even better.

Please send the PR.

**Comment by dvukolov** [comment]
Replacing zero-length messages with newline characters is possible. We would need to create a local copy of such a LogRecord in order to preserve the original message intact and keep the output of other handlers correct. Changes to the original message would otherwise be propagated to other handlers, resulting in double newlines.

The same is technically true for sending a dict as a JSON dump: one might expect to see str(dict) or repr(dict) in the console, but would obtain JSON. I assume that it's not our intent to interfere with processing of zero-length messages or dicts by other handlers.

**Comment by kislyuk** [comment]
I like the idea of replacing empty messages with an empty dict `{}` instead of a space or newline. Any objections to that?

**Comment by dvukolov** [comment]
I can't seem to make CloudWatch treat an empty dict as a newline (to preserve the original message format). In case of the above docker example, CloudWatch displays curly braces instead of newlines. Perhaps I'm doing something wrong.

**Comment by kislyuk** [comment]
Zero length messages are now ignored.
