### ISSUE TITLE
Unable write logs to custom log group and custom log stream.

### ISSUE THREAD

**Issue by ssrikanta-scea** [kislyuk/watchtower#61]
Below is my sample, code when ever my lambda function executes, it has to write logs to my custom log group name **randomLogs**, and to log stream **logger**, but when i execute below code isee log group and log stream are getting created but logs are still going to default lambda group and not for custom one,

@kislyuk please have look :eyes:   and help me.

```
import logging
import sys
import watchtower, logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

cl_handler = watchtower.CloudWatchLogHandler(log_group="randomLogs",
stream_name="logger", )
logger.addHandler(cl_handler)

def random_string(event, context):
    logger.warn("Hello from Lambda")
    return "Hello from Lambda"
```

**Comment by robertpeteuil** [comment]
I just had this exact problem!

I fixed it by inserting the command `logging.shutdown()` at the end of my function, on the line before the  `return` statement.

My theory is that the queues aren't getting flushed due to the way that Lambda terminates the function when it completes.

Let me know if this works for you!

**Comment by kislyuk** [comment]
This is a fundamental limitation of Lambda's preemptible API. To avoid log buffer loss when the lambda is frozen, follow @robertpeteuil's advice to flush the buffer before returning to your caller in the lambda.
