### ISSUE TITLE
missing LogRecord attributes

### ISSUE THREAD

**Issue by jesusch** [kislyuk/watchtower#90]
maybe Im to blind - but it seems to me this handler only emits timestamp + message?
what about other information like severity, module, or extra_args?

**Comment by eko-wibowo** [comment]
pretty sure this is from the boto3 API https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/logs.html#CloudWatchLogs.Client.put_log_events

interested to hear how the other workaround this limitation, filtering on level seems pretty useful, and stacktrace during exception. One way I can think of is to embed all those information in the message itself since we can define custom formatter

**Comment by kislyuk** [comment]
Watchtower provides a log handler. It does not provide a log formatter, and it is formatter agnostic. It's up to the implementer to define a log formatter that suits their needs.
